#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1
start_service() {
 procd_open_instance
 procd_set_param command /usr/sbin/t95h-gpu-start
 procd_set_param stdout 1
 procd_set_param stderr 1
 procd_close_instance
}
# No respawn and no live unloading of power-domain or GPU drivers.
